server.port=8081
spring.application.name=DriverService

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/swiftserve_driver
spring.datasource.username=root
spring.datasource.password=shlok6123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
