spring.datasource.url=jdbc:mysql://localhost:3306/swiftserve_db
spring.datasource.username=root
spring.datasource.password=shlok6123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Security / Performance tuning
server.error.include-stacktrace=never
spring.jpa.open-in-view=false
